# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# DATABASE (Local PostgreSQL)
# ===============================
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/clinicbilling}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# LIQUIBASE
# ===============================
spring.liquibase.change-log=classpath:db/changelogs/db.changelog-master.xml


# ===============================
# SWAGGER / SPRINGDOC
# ===============================
springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/api-docs

# ===============================
# LOGGING
# ===============================
logging.level.org.springframework=DEBUG
logging.level.org.springdoc=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.deepan.billing=DEBUG